{% set version = "1.5.7" %}
{% set sha256 = "be17bae0fd7f43f58d865b26f2c5755b624c5b93311a9f4f4756dd683e2941c3" %}
{% set python_min = "3.8" %}

package:
  name: pysr
  version: {{ version }}

source:
  - url: https://github.com/MilesCranmer/PySR/archive/v{{ version }}.tar.gz
    sha256: {{ sha256 }}

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps --ignore-installed
requirements:
  host:
    - python {{ python_min }}.*
    - pip
    - setuptools >=50.0.0
    - sympy >=1.0.0,<2.0.0
    - pandas >=0.21.0,<3.0.0
    - numpy >=1.13.0,<3.0.0
    - scikit-learn >=1.0.0,<2.0.0
    - pyjuliacall >=0.9.24,<0.9.25
    - click >=7.0.0,<9.0.0
    - typing-extensions >=4.0.0,<5.0.0
  run:
    - python >={{ python_min }}
    - {{ pin_compatible('numpy') }}
    - sympy >=1.0.0,<2.0.0
    - pandas >=0.21.0,<3.0.0
    - scikit-learn >=1.0.0,<2.0.0
    - pyjuliacall >=0.9.24,<0.9.25
    - click >=7.0.0,<9.0.0
    - typing-extensions >=4.0.0,<5.0.0
    - setuptools >=50.0.0

test:
  imports:
    - pysr
  requires:
    - pip
    - python {{ python_min }}
  commands:
    - pip check
    - python -m pysr test main

about:
  home: https://github.com/MilesCranmer/PySR
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: Simple, fast, and parallelized symbolic regression in Python
  description: |
    PySR is a simple, fast, and parallelized symbolic regression package for Python and Julia, which makes use of an algorithm based on regularized evolution and simulated annealing.
  doc_url: https://ai.damtp.cam.ac.uk/pysr
  dev_url: https://github.com/MilesCranmer/PySR

extra:
  recipe-maintainers:
    - MilesCranmer
