{% set version = "0.17.3" %}
{% set sha256 = "38ba7648a480acf73a385089bb93e3a0c31f52369deda75483fda156bbaa42cd" %}

package:
  name: pysr
  version: {{ version }}

source:
  - url: https://github.com/MilesCranmer/PySR/archive/v{{ version }}.tar.gz
    sha256: {{ sha256 }}

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps --ignore-installed
requirements:
  host:
    - python >=3.7,<4.0
    - pip
    - sympy >=1.0.0,<2.0.0
    - pandas >=0.21.0,<3.0.0
    - numpy >=1.13.0,<2.0.0
    - scikit-learn >=1.0.0,<2.0.0
    - pyjuliacall >=0.9.15,<0.9.16
    - click >=7.0.0,<9.0.0
    - typing_extensions >=4.0.0,<5.0.0
  run:
    - python >=3.7,<4.0
    - {{ pin_compatible('numpy') }}
    - sympy >=1.0.0,<2.0.0
    - pandas >=0.21.0,<3.0.0
    - scikit-learn >=1.0.0,<2.0.0
    - pyjuliacall >=0.9.15,<0.9.16
    - click >=7.0.0,<9.0.0
    - setuptools >=50.0.0
    - typing_extensions >=4.0.0,<5.0.0

test:
  imports:
    - pysr
  requires:
    - pip
  commands:
    - pip check
    - python -m pysr test main

about:
  home: https://github.com/MilesCranmer/PySR
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: Simple, fast, and parallelized symbolic regression in Python
  description: |
    PySR is a simple, fast, and parallelized symbolic regression package for Python and Julia, which makes use of an algorithm based on regularized evolution and simulated annealing.
  doc_url: https://astroautomata.com/PySR
  dev_url: https://github.com/MilesCranmer/PySR

extra:
  recipe-maintainers:
    - MilesCranmer
