{% set version = "0.7.0-1" %}

package:
  name: pysr
  version: {{ version }}

source:
  - url: https://github.com/MilesCranmer/PySR/archive/v{{ version }}.tar.gz
    sha256: 76b78e2dc265902a6ed79eab390696592ce3a8bac03f667c56892716546d1deb

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv && {{ PYTHON }} -c 'import pysr; pysr.install()'

requirements:
  build:
    - python
    - pip
    - pyjulia >=0.5.7
  host:
    - python >=3.6,<4.0
    - pip
    - pyjulia >=0.5.7
    - numpy >=1.14.0
    - pandas
    - sympy
    - scikit-learn
  run:
    - python >=3.6,<4.0
    - {{ pin_compatible('pyjulia') }}
    - {{ pin_compatible('numpy') }}
    - {{ pin_compatible('pandas') }}
    - {{ pin_compatible('sympy') }}
    - {{ pin_compatible('scikit-learn') }}

test:
  imports:
    - pysr
  requires:
    - pip
  commands:
    - pip check
    - python -c 'import pysr; pysr.install(); from pysr.sr import init_julia; init_julia()'

about:
  home: https://github.com/MilesCranmer/PySR
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: Simple, fast, and parallelized symbolic regression in Python
  description: |
    PySR is a simple, fast, and parallelized symbolic regression package for Python and Julia, which makes use of an algorithm based on regularized evolution and simulated annealing.
  doc_url: https://pysr.readthedocs.io/en/latest/?badge=latest
  dev_url: https://github.com/MilesCranmer/PySR

extra:
  recipe-maintainers:
    - MilesCranmer
